{% set name = "gawk" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 03a0360edcd84bec156fe211bbc4fc8c78790973ce4e8b990a11d778d40b1a26
    patches:
      - 0004-Fix-AM_TEST-no-more-or-localenl.patch
      - 0005-Fix-IN_TEST-no-more-or-localenl.patch
  - url: http://git.savannah.gnu.org/cgit/{{ name }}.git/plain/bootstrap.sh?h={{ name }}-{{ version }}
    sha256: 34fef05a25afdbe00edeffd1defa6d0578257651454fa2295d03db15b88358b3

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1
{% endif %}
  skip: true  # [win]
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
    - {{ compiler('c') }}
{% if bootstrapping != 'yes' %}
    - make  # [unix]
  host:
    - gettext   # [osx]
    - readline  # [osx]
{% endif %}

test:
  commands:
    - gawk --version
    - gawk --help
    - awk --version
    - awk --help

about:
  home: https://www.gnu.org/software/gawk/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: |
    The awk utility interprets a special-purpose programming language that
    makes it easy to handle simple data-reformatting jobs.
  doc_url: https://www.gnu.org/software/gawk/manual/gawk.html
  dev_url: http://savannah.gnu.org/projects/gawk/
  description: |
    The GNU implementation of awk is called gawk; if you invoke it with the
    proper options or environment variables, it is fully compatible with the
    POSIX1 specification of the awk language and with the Unix version of awk
    maintained by Brian Kernighan. This means that all properly written awk
    programs should work with gawk. So most of the time, we don’t distinguish
    between gawk and other awk implementations.

extra:
  recipe-maintainers:
    - bollwyvl
