{% set name = "gawk" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 2d686c9a5b7ba292bc3fa56bc84a1959d721a9d57970a76413156d4b8f1fc67d
    patches:
      - 0004-Do-no-more.patch
  - url: http://git.savannah.gnu.org/cgit/{{ name }}.git/plain/bootstrap.sh?h={{ name }}-{{ version }}
    sha256: 34fef05a25afdbe00edeffd1defa6d0578257651454fa2295d03db15b88358b3


build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - gettext   # [osx]
    - readline  # [osx]

test:
  commands:
    - gawk --version
    - gawk --help
    - awk --version
    - awk --help

about:
  home: https://www.gnu.org/software/gawk/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: |
    The awk utility interprets a special-purpose programming language that
    makes it easy to handle simple data-reformatting jobs.
  doc_url: https://www.gnu.org/software/gawk/manual/gawk.html
  dev_url: http://savannah.gnu.org/projects/gawk/
  description: |
    The GNU implementation of awk is called gawk; if you invoke it with the
    proper options or environment variables, it is fully compatible with the
    POSIX1 specification of the awk language and with the Unix version of awk
    maintained by Brian Kernighan. This means that all properly written awk
    programs should work with gawk. So most of the time, we don’t distinguish
    between gawk and other awk implementations.

extra:
  recipe-maintainers:
    - bollwyvl
